<Type Name="StackOverflowException" FullName="System.StackOverflowException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="2a740d20961d222fa2a2d96997b764c8eb151c60" />
    <Meta Name="ms.sourcegitcommit" Value="0ec122ee5f3681159b8460ab15b409fd6e3d3ae0" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="pt-BR" />
    <Meta Name="ms.lasthandoff" Value="10/04/2018" />
    <Meta Name="ms.locfileid" Value="48712452" />
  </Metadata>
  <TypeSignature Language="C#" Value="public sealed class StackOverflowException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit StackOverflowException extends System.SystemException" />
  <TypeSignature Language="DocId" Value="T:System.StackOverflowException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class StackOverflowException&#xA;Inherits SystemException" />
  <TypeSignature Language="C++ CLI" Value="public ref class StackOverflowException sealed : SystemException" />
  <TypeSignature Language="F#" Value="type StackOverflowException = class&#xA;    inherit SystemException" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>1.0.5000.0</AssemblyVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
    <Attribute FrameworkAlternate="netframework-1.1;netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="d0ca6-101">A exceção gerada quando a pilha de execução estoura por conter chamadas de método aninhadas em excesso.</span>
      <span class="sxs-lookup">
        <span data-stu-id="d0ca6-101">The exception that is thrown when the execution stack overflows because it contains too many nested method calls.</span>
      </span>
      <span data-ttu-id="d0ca6-102">Essa classe não pode ser herdada.</span>
      <span class="sxs-lookup">
        <span data-stu-id="d0ca6-102">This class cannot be inherited.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d0ca6-103"><xref:System.StackOverflowException> é lançada para erros de estouro de pilha de execução, normalmente em caso de uma recursão muito profunda ou irrestrita.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-103"><xref:System.StackOverflowException> is thrown for execution stack overflow errors, typically in case of a very deep or unbounded recursion.</span></span>  
  
 <span data-ttu-id="d0ca6-104"><xref:System.StackOverflowException> usa o HRESULT COR_E_STACKOVERFLOW, que tem o valor 0x800703E9.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-104"><xref:System.StackOverflowException> uses the HRESULT COR_E_STACKOVERFLOW, which has the value 0x800703E9.</span></span> <span data-ttu-id="d0ca6-105">O <xref:System.Reflection.Emit.OpCodes.Localloc> instrução de linguagem intermediária (IL) gera <xref:System.StackOverflowException>.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-105">The <xref:System.Reflection.Emit.OpCodes.Localloc> intermediate language (IL) instruction throws <xref:System.StackOverflowException>.</span></span> <span data-ttu-id="d0ca6-106">Para obter uma lista de valores de propriedade inicial para uma <xref:System.StackOverflowException> do objeto, consulte o <xref:System.StackOverflowException.%23ctor%2A> construtores.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-106">For a list of initial property values for a <xref:System.StackOverflowException> object, see the <xref:System.StackOverflowException.%23ctor%2A> constructors.</span></span>  
  
## <a name="version-considerations"></a><span data-ttu-id="d0ca6-107">Considerações da versão</span><span class="sxs-lookup"><span data-stu-id="d0ca6-107">Version Considerations</span></span>  
 <span data-ttu-id="d0ca6-108">No .NET Framework 1.0 e 1.1, você pode capturar uma <xref:System.StackOverflowException> objeto (por exemplo, para se recuperar de recursão não limitada).</span><span class="sxs-lookup"><span data-stu-id="d0ca6-108">In the .NET Framework 1.0 and 1.1, you could catch a <xref:System.StackOverflowException> object (for example, to recover from unbounded recursion).</span></span> <span data-ttu-id="d0ca6-109">Começando com o .NET Framework 2.0, você não pode capturar uma <xref:System.StackOverflowException> do objeto com um `try` / `catch` bloco e o processo correspondente é terminada por padrão.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-109">Starting with the .NET Framework 2.0, you can’t catch a <xref:System.StackOverflowException> object with a `try`/`catch` block, and the corresponding process is terminated by default.</span></span> <span data-ttu-id="d0ca6-110">Consequentemente, você deve escrever seu código para detectar e impedir que um estouro de pilha.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-110">Consequently, you should write your code to detect and prevent a stack overflow.</span></span> <span data-ttu-id="d0ca6-111">Por exemplo, se seu aplicativo depender de recursão, use um contador ou uma condição de estado para encerrar o loop recursivo.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-111">For example, if your app depends on recursion, use a counter or a state condition to terminate the recursive loop.</span></span> <span data-ttu-id="d0ca6-112">O exemplo a seguir usa um contador para garantir que o número de recursiva chamadas para o `Execute` método não exceder o máximo definido pela constante MAX_RECURSIVE_CALLS.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-112">The following example uses a counter to ensure that the number of recursive calls to the `Execute` method do not exceed a maximum defined by the MAX_RECURSIVE_CALLS constant.</span></span>  
  
 [!code-csharp[System.StackOverflowException.Class#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.stackoverflowexception.class/cs/example1a.cs#1)]
 [!code-vb[System.StackOverflowException.Class#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.stackoverflowexception.class/vb/example1a.vb#1)]  
  
> [!NOTE]
>  <span data-ttu-id="d0ca6-113">Aplicando o <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> de atributo para um método que lança um <xref:System.StackOverflowException> não tem nenhum efeito.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-113">Applying the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> attribute to a method that throws a <xref:System.StackOverflowException> has no effect.</span></span> <span data-ttu-id="d0ca6-114">Você ainda não é possível tratar a exceção do código do usuário.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-114">You still cannot handle the exception from user code.</span></span>  
  
 <span data-ttu-id="d0ca6-115">Se seu aplicativo hospeda o common language runtime (CLR), pode especificar que o CLR deve descarregar o domínio do aplicativo onde a exceção de estouro de pilha ocorre e permitir que o processo correspondente continue.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-115">If your app hosts the common language runtime (CLR), it can specify that the CLR should unload the application domain where the stack overflow exception occurs and let the corresponding process continue.</span></span> <span data-ttu-id="d0ca6-116">Para obter mais informações, consulte [ICLRPolicyManager Interface](~/docs/framework/unmanaged-api/hosting/iclrpolicymanager-interface.md).</span><span class="sxs-lookup"><span data-stu-id="d0ca6-116">For more information, see [ICLRPolicyManager Interface](~/docs/framework/unmanaged-api/hosting/iclrpolicymanager-interface.md).</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="T:System.Exception" />
    <related type="Article" href="~/docs/standard/exceptions/index.md">
      <span data-ttu-id="d0ca6-117">Manipulando e lançando exceções</span>
      <span class="sxs-lookup">
        <span data-stu-id="d0ca6-117">Handling and Throwing Exceptions</span>
      </span>
    </related>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="d0ca6-118">Inicializa uma nova instância da classe <see cref="T:System.StackOverflowException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-118">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public StackOverflowException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.StackOverflowException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; StackOverflowException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="d0ca6-119">Inicializa uma nova instância da classe <see cref="T:System.StackOverflowException" />, configurando a propriedade <see cref="P:System.Exception.Message" /> da nova instância como uma mensagem fornecida pelo sistema que descreve o erro, como "A operação solicitada causou um excedente de pilha."</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-119">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class, setting the <see cref="P:System.Exception.Message" /> property of the new instance to a system-supplied message that describes the error, such as "The requested operation caused a stack overflow."</span>
          </span>
          <span data-ttu-id="d0ca6-120">Esta mensagem leva em conta a cultura do sistema atual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-120">This message takes into account the current system culture.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d0ca6-121">A tabela a seguir mostra os valores de propriedade iniciais para uma instância de <xref:System.StackOverflowException>.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-121">The following table shows the initial property values for an instance of <xref:System.StackOverflowException>.</span></span>  
  
|<span data-ttu-id="d0ca6-122">Propriedade</span><span class="sxs-lookup"><span data-stu-id="d0ca6-122">Property</span></span>|<span data-ttu-id="d0ca6-123">Valor</span><span class="sxs-lookup"><span data-stu-id="d0ca6-123">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="d0ca6-124">`null`.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-124">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="d0ca6-125">A cadeia de caracteres da mensagem de erro localizada.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-125">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public StackOverflowException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.StackOverflowException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; StackOverflowException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new StackOverflowException : string -&gt; StackOverflowException" Usage="new System.StackOverflowException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="d0ca6-126">Um <see cref="T:System.String" /> que descreve o erro.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-126">A <see cref="T:System.String" /> that describes the error.</span>
          </span>
          <span data-ttu-id="d0ca6-127">O conteúdo da mensagem deve ser compreendido por humanos.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-127">The content of message is intended to be understood by humans.</span>
          </span>
          <span data-ttu-id="d0ca6-128">O chamador desse construtor é necessário para garantir que essa cadeia de caracteres tenha sido localizada para a cultura do sistema atual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-128">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="d0ca6-129">Inicializa uma nova instância da classe <see cref="T:System.StackOverflowException" /> com uma mensagem de erro especificada.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-129">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class with a specified error message.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d0ca6-130">A tabela a seguir mostra os valores de propriedade iniciais para uma instância de <xref:System.StackOverflowException>.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-130">The following table shows the initial property values for an instance of <xref:System.StackOverflowException>.</span></span>  
  
|<span data-ttu-id="d0ca6-131">Propriedade</span><span class="sxs-lookup"><span data-stu-id="d0ca6-131">Property</span></span>|<span data-ttu-id="d0ca6-132">Valor</span><span class="sxs-lookup"><span data-stu-id="d0ca6-132">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="d0ca6-133">Uma referência nula (`Nothing` no Visual Basic).</span><span class="sxs-lookup"><span data-stu-id="d0ca6-133">A null reference (`Nothing` in Visual Basic).</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="d0ca6-134">A cadeia de caracteres da mensagem de erro.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-134">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public StackOverflowException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.StackOverflowException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; StackOverflowException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new StackOverflowException : string * Exception -&gt; StackOverflowException" Usage="new System.StackOverflowException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="d0ca6-135">A mensagem de erro que explica a razão da exceção.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-135">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="d0ca6-136">A exceção que é a causa da exceção atual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-136">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="d0ca6-137">Se o parâmetro <c>innerException</c> não é uma referência nula (<see langword="Nothing" /> no Visual Basic), a exceção atual é gerada em um bloco <see langword="catch" /> que trata a exceção interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-137">If the <c>innerException</c> parameter is not a null reference (<see langword="Nothing" /> in Visual Basic), the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="d0ca6-138">Inicializa uma nova instância da classe <see cref="T:System.StackOverflowException" /> com uma mensagem de erro especificada e uma referência à exceção interna que é a causa da exceção.</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-138">Initializes a new instance of the <see cref="T:System.StackOverflowException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d0ca6-139">Uma exceção que é lançada como um resultado direto de uma exceção anterior pode incluir uma referência para a exceção anterior na propriedade <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-139">An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="d0ca6-140">A propriedade <xref:System.Exception.InnerException%2A> retorna o mesmo valor que é passado para o construtor ou uma referência nula (`Nothing` no Visual Basic) caso a propriedade <xref:System.Exception.InnerException%2A> não forneça o valor de exceção interna para o construtor.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-140">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="d0ca6-141">A tabela a seguir mostra os valores de propriedade iniciais para uma instância de <xref:System.StackOverflowException>.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-141">The following table shows the initial property values for an instance of <xref:System.StackOverflowException>.</span></span>  
  
|<span data-ttu-id="d0ca6-142">Propriedade</span><span class="sxs-lookup"><span data-stu-id="d0ca6-142">Property</span></span>|<span data-ttu-id="d0ca6-143">Valor</span><span class="sxs-lookup"><span data-stu-id="d0ca6-143">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="d0ca6-144">A referência de exceção interna.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-144">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="d0ca6-145">A cadeia de caracteres da mensagem de erro.</span><span class="sxs-lookup"><span data-stu-id="d0ca6-145">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
        <related type="Article" href="~/docs/standard/exceptions/index.md">
          <span data-ttu-id="d0ca6-146">Manipulando e lançando exceções</span>
          <span class="sxs-lookup">
            <span data-stu-id="d0ca6-146">Handling and Throwing Exceptions</span>
          </span>
        </related>
      </Docs>
    </Member>
  </Members>
</Type>