<Type Name="InvalidPipelineStoreException" FullName="System.AddIn.Hosting.InvalidPipelineStoreException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="9bbe4e4cfa38c1fd53c0b87c4aacce4d1e815312" />
    <Meta Name="ms.sourcegitcommit" Value="d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="pt-BR" />
    <Meta Name="ms.lasthandoff" Value="04/03/2018" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class InvalidPipelineStoreException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit InvalidPipelineStoreException extends System.Exception" />
  <TypeSignature Language="DocId" Value="T:System.AddIn.Hosting.InvalidPipelineStoreException" />
  <TypeSignature Language="VB.NET" Value="Public Class InvalidPipelineStoreException&#xA;Inherits Exception" />
  <TypeSignature Language="C++ CLI" Value="public ref class InvalidPipelineStoreException : Exception" />
  <AssemblyInfo>
    <AssemblyName>System.AddIn</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="4d24d-101">A exceção que será gerada quando um diretório não for encontrado e o usuário não tiver permissão para acessar o caminho raiz do pipeline ou um caminho de suplemento.</span>
      <span class="sxs-lookup">
        <span data-stu-id="4d24d-101">The exception that is thrown when a directory is not found and the user does not have permission to access the pipeline root path or an add-in path.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="4d24d-102">Ao contrário de <xref:System.IO.DirectoryNotFoundException>, essa exceção não fornece nenhuma informação de caminho.</span><span class="sxs-lookup"><span data-stu-id="4d24d-102">Unlike <xref:System.IO.DirectoryNotFoundException>, this exception does not provide any path information.</span></span> <span data-ttu-id="4d24d-103">Isso impede que um usuário mal-intencionado deliberadamente especifique caminhos incorretos e use as informações retornadas pela exceção para determinar os caminhos reais.</span><span class="sxs-lookup"><span data-stu-id="4d24d-103">This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.</span></span>  
  
 <span data-ttu-id="4d24d-104">Essa exceção é gerada pelos seguintes métodos de descoberta que criar e atualizar o armazenamento de informações do suplemento e pipeline: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, e <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>.</span><span class="sxs-lookup"><span data-stu-id="4d24d-104">This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, and <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="4d24d-105">Inicializa uma nova instância da classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-105">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public InvalidPipelineStoreException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; InvalidPipelineStoreException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="4d24d-106">Inicializa uma nova instância da classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-106">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public InvalidPipelineStoreException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; InvalidPipelineStoreException(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="4d24d-107">Uma descrição do erro.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-107">A description of the error.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4d24d-108">Inicializa uma nova instância da classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> com a mensagem especificada.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-108">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class with the specified message.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected InvalidPipelineStoreException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; InvalidPipelineStoreException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="4d24d-109">Os dados de objeto serializados.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-109">The serialized object data.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="4d24d-110">As informações contextuais sobre os dados de objeto de origem ou de destino.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-110">The contextual information about the source or destination object data.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4d24d-111">Inicializa uma nova instância da classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> com informações de serialização e de contexto de streaming.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-111">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class with serialization and streaming context information.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="4d24d-112">Este construtor é chamado durante a desserialização para reconstituir a um objeto de exceção que é transmitido em um fluxo.</span><span class="sxs-lookup"><span data-stu-id="4d24d-112">This constructor is called during deserialization to reconstitute an exception object that is transmitted over a stream.</span></span> <span data-ttu-id="4d24d-113">Para obter mais informações, consulte [XML e serialização SOAP](~/docs/standard/serialization/xml-and-soap-serialization.md).</span><span class="sxs-lookup"><span data-stu-id="4d24d-113">For more information, see [XML and SOAP Serialization](~/docs/standard/serialization/xml-and-soap-serialization.md).</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public InvalidPipelineStoreException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; InvalidPipelineStoreException(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.AddIn</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="4d24d-114">Uma descrição do erro.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-114">A description of the error.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="4d24d-115">A exceção que é a causa da exceção atual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-115">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="4d24d-116">Caso o parâmetro <c>innerException</c> não seja uma referência nula, exceção atual será acionada em um bloco catch que manipula a exceção interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-116">If the <c>innerException</c> parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4d24d-117">Inicializa uma nova instância da classe <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> com a mensagem especificada e uma referência à exceção interna que é a causa dessa exceção.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4d24d-117">Initializes a new instance of the <see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /> class with the specified message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="4d24d-118">Uma exceção que é lançada como um resultado direto de uma exceção anterior deve incluir uma referência para a exceção anterior na propriedade <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="4d24d-118">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="4d24d-119">O <xref:System.Exception.InnerException%2A> propriedade retorna o mesmo valor que é passado para o construtor, ou uma referência nula se o <xref:System.Exception.InnerException%2A> propriedade não fornecer o valor da exceção interna para o construtor.</span><span class="sxs-lookup"><span data-stu-id="4d24d-119">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed to the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="4d24d-120">A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException> classe.</span><span class="sxs-lookup"><span data-stu-id="4d24d-120">The following table shows the initial property values for an instance of the <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException> class.</span></span>  
  
|<span data-ttu-id="4d24d-121">Propriedade</span><span class="sxs-lookup"><span data-stu-id="4d24d-121">Property</span></span>|<span data-ttu-id="4d24d-122">Valor</span><span class="sxs-lookup"><span data-stu-id="4d24d-122">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="4d24d-123">A referência de exceção interna.</span><span class="sxs-lookup"><span data-stu-id="4d24d-123">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="4d24d-124">A cadeia de caracteres da mensagem de erro localizada.</span><span class="sxs-lookup"><span data-stu-id="4d24d-124">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>