<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="ExceptionDispatchInfo.xml" source-language="en-US" target-language="pt-BR">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5c9705c7cab056ffd2d3a6a05962a03c0ae933d19.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">c9705c7cab056ffd2d3a6a05962a03c0ae933d19</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-1.0,netstandard-1.1,netstandard-1.2,netstandard-1.3,netstandard-1.4,netstandard-1.5,netstandard-1.6,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>Represents an exception whose state is captured at a certain point in code.</source>
          <target state="translated">Representa uma exceção cujo estado é capturado em um determinado ponto no código.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>The <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> object stores the stack trace information and Watson information that the exception contains at the point where it is captured.</source>
          <target state="translated">O <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> objeto armazena as informações de rastreamento de pilha e Watson que contém a exceção no ponto em que eles são capturados.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>The exception can be thrown at another time and possibly on another thread by calling the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A?displayProperty=nameWithType&gt;</ph> method.</source>
          <target state="translated">A exceção pode ser lançada em outro momento e, possivelmente em outro thread chamando o <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A?displayProperty=nameWithType&gt;</ph> método.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source>The exception is thrown as if it had flowed from the point where it was captured to the point where the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph> method is called.</source>
          <target state="translated">A exceção é gerada como se ele tivesse flui do ponto em que ele foi capturado para o ponto em que o <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph> método é chamado.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo">
          <source><ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> cannot be serialized and is not intended to cross application domain boundaries.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> não pode ser serializado e não deve ultrapassar os limites de domínio de aplicativo.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>The exception whose state is captured, and which is represented by the returned object.</source>
          <target state="translated">A exceção cujo estado é capturado e que é representada pelo objeto retornado.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>Creates an <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> object that represents the specified exception at the current point in code.</source>
          <target state="translated">Cria um objeto <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> que representa a exceção especificada no ponto atual no código.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>An object that represents the specified exception at the current point in code.</source>
          <target state="translated">Um objeto que representa a exceção especificada no ponto atual no código.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>You can use the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> object that is returned by this method at another time and possibly on another thread to rethrow the specified exception, as if the exception had flowed from this point where it was captured to the point where it is rethrown.</source>
          <target state="translated">Você pode usar o <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo&gt;</ph> objeto que é retornado por este método em outro momento e, possivelmente em outro thread relançar a exceção especificada, como se a exceção tivesse fluxo desse ponto em que ele foi capturado para o ponto em que é lançada novamente.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>If the exception is active when it is captured, the current stack trace information and Watson information that is contained in the exception is stored.</source>
          <target state="translated">Se a exceção estiver ativo quando ele é capturado, as informações de rastreamento de pilha atual e informações de Watson que estão contidas na exceção é armazenada.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source>If it is inactive, that is, if it has not been thrown, it will not have any stack trace information or Watson information.</source>
          <target state="translated">Se ela estiver inativa, ou seja, se não tiver sido lançada, ele não terá quaisquer informações de rastreamento de pilha ou informações sobre Watson.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(System.Exception)">
          <source><ph id="ph1">&lt;paramref name="source" /&gt;</ph> is <ph id="ph2">&lt;see langword="null" /&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">&lt;paramref name="source" /&gt;</ph> é <ph id="ph2">&lt;see langword="null" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>Gets the exception that is represented by the current instance.</source>
          <target state="translated">Obtém a exceção que é representada pela instância atual.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>The exception that is represented by the current instance.</source>
          <target state="translated">A exceção que é representada pela instância atual.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>This property is used by the Task Parallel Library, for example, to combine multiple exceptions in an <ph id="ph1">&lt;xref:System.AggregateException&gt;</ph> object.</source>
          <target state="translated">Essa propriedade é usada pela biblioteca de tarefas paralelas, por exemplo, para combinar várias exceções em uma <ph id="ph1">&lt;xref:System.AggregateException&gt;</ph> objeto.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>It is not intended to be used by application code.</source>
          <target state="translated">Ele não se destina a ser usado pelo código do aplicativo.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException">
          <source>Use the <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph> method to restore the state of the captured exception and throw it.</source>
          <target state="translated">Use o <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2A&gt;</ph> método para restaurar o estado da exceção capturada e lança-lo.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw">
          <source>Throws the exception that is represented by the current <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> object, after restoring the state that was saved when the exception was captured.</source>
          <target state="translated">Gera a exceção que é representada pelo objeto <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.ExceptionDispatchInfo" /&gt;</ph> atual depois de restaurar o estado salvo quando a exceção foi capturada.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw">
          <source>When the exception is restored, the following string is inserted in the stack trace to indicate the restore point: "End of stack trace from the previous location where the exception was thrown".</source>
          <target state="translated">Quando a exceção é restaurada, a cadeia de caracteres a seguir é inserida no rastreamento de pilha para indicar o ponto de restauração: "Fim do rastreamento de pilha do local anterior onde a exceção foi lançada".</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw">
          <source>This is similar to the way inner exceptions or marshaled exceptions are indicated in stack traces.</source>
          <target state="translated">Isso é semelhante à forma como exceções internas ou empacotadas exceções são indicadas em rastreamentos de pilha.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>